routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('groupclient','GroupclientController');
    Route::resource('clientservice','ClientserviceController');
    Route::resource('client','ClientController');
    Route::get('clientReport','ClientController@clientReport')->name('clientReport');
   Route::get('/clientInvoice/{id}', 'ClientController@clientInvoice');



    Route::resource('groupsupplier','GroupsupplierController');
    Route::resource('supplier','SupplierController');
    Route::get('supplierReport','SupplierController@supplierReport')->name('supplierReport');
    Route::resource('item','ItemController');
    Route::resource('product','ProductController');
    Route::get('productReport','ProductController@productReport')->name('productReport');
    Route::resource('purchase','PurchaseController');
    Route::get('purchaseReport','PurchaseController@purchaseReport')->name('purchaseReport');
    Route::resource('retire','RetireController');
    Route::resource('invoice','InvoiceController');

});


Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('groupclient','GroupclientController');
    Route::resource('clientservice','ClientserviceController');
    Route::resource('client','ClientController');
    Route::get('clientReport','ClientController@clientReport')->name('clientReport');
    Route::get('/clientInvoice/{id}', 'ClientController@clientInvoice');
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\SoftDeletes;
class Client extends Model
{

  //  use SoftDeletes;
    protected $fillable =['name','phone','email','web_address','address','reference','reference_value','progress','advance','due','total','status','groupclient_id','clientservice_id'];


    public function scopeIndex($query){
        return $query->orderBy('id','DESC')->get();
    }

    public function scopeTrash($query)
    {
        return $query->onlyTrashed()->orderBy('id', 'desc')->get();
    }
    public function groupclients()
    {
        return $this->belongsToMany('App\Groupclient')->withTimestamps();
    }

    public function clientservices()
    {
        return $this->belongsToMany('App\Clientservice')->withTimestamps();
    }

    public function invoice()
    {
        return $this->belongsTo('App\Invoice');
    }


}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Groupclient;
use App\Clientservice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Client;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->get();
        return view('admin.client.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $groupclients = Groupclient::all();
        $clientservices = Clientservice::all();
        return view('admin.client.create', compact('groupclients','clientservices'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Client $client)
    {
        $client = new Client;
        $client->date = $request->date;
        $client->name = $request->name;
        $client->address= $request->address;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->web_address = $request->web_address;
        $client->reference = $request->reference;
        $client->reference_value = $request->reference_value;
        $client->done = $request->done;
        $client->running= $request->running;
        $client->not_complete= $request->not_complete;
        $client->timeline= $request->timeline;
        $client->progress= $request->progress;
        $client->pp_date= $request->pp_date;
        $client->advance= $request->advance;
        $client->total= $request->total;
        $client->status= $request->status;
        $client->save();

        $client->groupclients()->attach($request->groupclients);
        $client->clientservices()->attach($request->clientservices);
        Toastr::success('Client Successfully Saved :)','Success');
        return redirect(route('admin.client.index'));

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Client $client)
    {
        return view('admin.client.show',compact('client'));
    }




    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $groupclients = Groupclient::all();
        $clientservices = Clientservice::all();
        $client= Client::where('id',$id)->first();
        return view('admin.client.edit',compact('client','groupclients','clientservices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::find($id);
        $client->date = $request->date;
        $client->name = $request->name;
        $client->address= $request->address;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->web_address = $request->web_address;
        $client->reference = $request->reference;
        $client->reference_value = $request->reference_value;
        $client->done = $request->done;
        $client->running= $request->running;
        $client->not_complete= $request->not_complete;
        $client->timeline= $request->timeline;
        $client->progress= $request->progress;
        $client->pp_date= $request->pp_date;
        $client->advance= $request->advance;
        $client->total= $request->total;
        $client->status= $request->status;
        $client->save();
        $client->groupclients()->sync($request->groupclients);
        $client->clientservices()->sync($request->clientservices);
        Toastr::success('Client Successfully Updated :)','Success');
        return redirect(route('admin.client.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Client::where('id',$id)->delete();
        return redirect()->back();
    }

    public function clientReport()
    {
        $clients = Client::latest()->get();
        return view('admin.client.clientReport', compact('clients'));
    }
//    public function clientInvoice( $id)
//    {
//        $client = Client::find($id);
//        return view('admin.client.clientInvoice',compact('client'));
//
//    }
    public function clientInvoice( $id)
    {
        $client = Client::find($id);
        return view('admin.client.clientInvoice',compact('client'));

    }


}

app/Http/Controllers/Author/ClientController.php
<?php

namespace App\Http\Controllers\Author;

use App\Groupclient;
use App\Clientservice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Client;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->get();
        return view('author.client.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $groupclients = Groupclient::all();
        $clientservices = Clientservice::all();
        return view('author.client.create', compact('groupclients','clientservices'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Client $client)
    {
        $client = new Client;
        $client->date = $request->date;
        $client->name = $request->name;
        $client->address= $request->address;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->web_address = $request->web_address;
        $client->reference = $request->reference;
        $client->reference_value = $request->reference_value;
        $client->done = $request->done;
        $client->running= $request->running;
        $client->not_complete= $request->not_complete;
        $client->timeline= $request->timeline;
        $client->progress= $request->progress;
        $client->pp_date= $request->pp_date;
        $client->advance= $request->advance;
        $client->total= $request->total;
        $client->status= $request->status;
        $client->save();

        $client->groupclients()->attach($request->groupclients);
        $client->clientservices()->attach($request->clientservices);
        Toastr::success('Client Successfully Saved :)','Success');
        return redirect(route('author.client.index'));

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Client $client)
    {
        return view('author.client.show',compact('client'));
    }




    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $groupclients = Groupclient::all();
        $clientservices = Clientservice::all();
        $client= Client::where('id',$id)->first();
        return view('author.client.edit',compact('client','groupclients','clientservices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::find($id);
        $client->date = $request->date;
        $client->name = $request->name;
        $client->address= $request->address;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->web_address = $request->web_address;
        $client->reference = $request->reference;
        $client->reference_value = $request->reference_value;
        $client->done = $request->done;
        $client->running= $request->running;
        $client->not_complete= $request->not_complete;
        $client->timeline= $request->timeline;
        $client->progress= $request->progress;
        $client->pp_date= $request->pp_date;
        $client->advance= $request->advance;
        $client->total= $request->total;
        $client->status= $request->status;
        $client->save();
        $client->groupclients()->sync($request->groupclients);
        $client->clientservices()->sync($request->clientservices);
        Toastr::success('Client Successfully Updated :)','Success');
        return redirect(route('author.client.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Client::where('id',$id)->delete();
        return redirect()->back();
    }

    public function clientReport()
    {
        $clients = Client::latest()->get();
        return view('author.client.clientReport', compact('clients'));
    }
//    public function clientInvoice( $id)
//    {
//        $client = Client::find($id);
//        return view('admin.client.clientInvoice',compact('client'));
//
//    }
    public function clientInvoice( $id)
    {
        $client = Client::find($id);
        return view('author.client.clientInvoice',compact('client'));

    }


}

resources/views/admin/client/clientReport.blade.php
@extends('layouts.backend.app')
@section('title','Client')

@push('css')
        <!-- JQuery DataTable Css -->
<link href="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <a  class="btn bg-primary waves-effect " href="{{ route('admin.client.create') }}">
                <i class="material-icons">add</i>
                <span>Add New Client </span>
            </a>
            <a  class="btn bg-primary waves-effect " href="{{ route('admin.client.index') }}">
                <i class="material-icons">arrow_back</i>
                <span>Back List </span>
            </a>
        </div>
        <!-- #END# Basic Examples -->
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            All Client Group
                            <span class="badge bg-blue">{{ $clients->count() }}</span>
                        </h2>


                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>

                                    <th>Name</th>
                                    <th>Group </th>
                                    <th>Done</th>
                                    <th>Running</th>
                                    <th>Not Complete</th>
                                    <th>Status</th>
                                    <th>Advance</th>
                                    <th>Due</th>
                                    <th>Total</th>




                                </tr>
                                </thead>
                                <tfoot>
                                <tr>

                                    <th>Name</th>
                                    <th>Group </th>
                                    <th>Done</th>
                                    <th>Running</th>
                                    <th>Not Complete</th>
                                    <th>Status</th>
                                    <th>Advance</th>
                                    <th>Due</th>
                                    <th>Total</th>


                                </tr>
                                </tfoot>
                                <tbody>



                                @foreach($clients as $client)
                                    <tr>

                                        <td>{{ $client->name}}</td>
                                        <td>   @foreach($client->groupclients as $groupclient)

                                                {{ $groupclient->name }} <br/>
                                            @endforeach</td>
                                        <td>{{ $client->done }}</td>
                                        <td>{{ $client->running }}</td>
                                        <td>{{ $client->not_complete}}</td>
                                        <td>{{ $client->status}}</td>
                                        <td>{{ $client->advance}}</td>
                                        <td>{{ $client->total-$client->advance}}</td>
                                        <td>{{ $client->total}}</td>



                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- #END# Exportable Table -->
    </div>
    @endsection

    @push('js')
            <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="{{ asset('backend/js/pages/tables/jquery-datatable.js') }}"></script>

    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
    <script type="text/javascript">
        function deletegroupclient(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-'+id).submit();
            }else if (
                    // Read more about handling dismissals
            result.dismiss === swal.DismissReason.cancel
            ) {
                swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                )
            }
        })
        }
    </script>
    @endpush

resources/views/admin/client/create.blade.php
@extends('layouts.backend.app')

@section('title','Client')

@push('css')
        <!-- Bootstrap Select Css -->
<link href="{{ asset('backend/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <form action="{{ route('admin.client.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADD  CLIENT INFO
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label class="form-label"> Project Start Date</label>
                                    <input type="date" id="date" class="form-control" name="date">

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                <input type="text" id="name" class="form-control" name="name">
                                <label class="form-label">Name</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="address" class="form-control" name="address">
                                    <label class="form-label"> Address</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="number" id="phone" class="form-control" name="phone">
                                  <label class="form-label"> Phone Number</label>
                                 </div>
                            </div>
                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="email" id="email" class="form-control" name="email">
                                  <label class="form-label"> E-mail</label>
                                  </div>
                            </div>

                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="web_address" id="web_address" class="form-control" name="web_address">
                                  <label class="form-label">Website Address</label>
                                  </div>
                            </div>

                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="text" id="reference" class="form-control" name="reference">
                                  <label class="form-label"> Reference</label>
                                 </div>
                            </div>

                            <div class="form-group form-float">
                                  <div class="form-line">
                                  <input type="number" id="reference_value" class="form-control" name="reference_value">
                                  <label class="form-label"> Reference value</label>
                                 </div>
                            </div>


                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                               Group And Service
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('groupclients') ? 'focused error' : '' }}">
                                    <label for="groupclient">Select Group</label>
                                    <select name="groupclients[]" id="groupclient" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($groupclients as $groupclient)
                                            <option value="{{ $groupclient->id }}">{{ $groupclient->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>


                        </div>
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line {{ $errors->has('clientservices') ? 'focused error' : '' }}">
                                    <label for="clientservice">Select Type of Service</label>
                                    <select name="clientservices[]" id="clientservice" class="form-control show-tick" data-live-search="true" multiple>
                                        @foreach($clientservices as $clientservice)
                                            <option value="{{ $clientservice->id }}">
                                                {{ $clientservice->name }}

                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <a  class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.client.index') }}">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button><br/>
                            <a  class="btn btn-info m-t-15 waves-effect" href="{{ route('admin.groupclient.create') }}">ADD GROUP</a>
                            <a  class="btn btn-info m-t-15 waves-effect" href="{{ route('admin.clientservice.create') }}">ADD SERVICE</a>

                        </div>


                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Progress
                            </h2>
                        </div>
                        <div class="body">


                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="done" id="done" class="form-control" name="done">
                                    <label class="form-label">Done Service</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="running" id="done" class="form-control" name="running">
                                    <label class="form-label"> Running Service</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="not_complete" id="not_complete" class="form-control" name="not_complete">
                                    <label class="form-label">Not Complete Service</label>
                                </div>
                            </div>


                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="timeline" class="form-control" name="timeline">
                                    <label class="form-label"> Timeline</label>
                                </div>
                            </div>
                            <div class="form-group form-float">

                                <label for="progress">Select Progress</label>
                                <select class="form-control show-tick" name="progress" id="progress" >
                                    <option></option>
                                    <option>Complete</option>
                                    <option>Not Complete</option>
                                    <option>Running</option>

                                </select>

                            </div>

                            </div>

                        </div>
                    </div>
                </div>


            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                               Payment
                            </h2>
                        </div>
                        <div class="body">

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="pp_date" class="form-control" name="pp_date">
                                    <label class="form-label"> Previous Payment Info </label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="total" class="form-control" name="total">
                                    <label class="form-label">Total</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="advance" class="form-control" name="advance">
                                    <label class="form-label"> Advance</label>
                                </div>
                            </div>


                            <div class="form-group form-float">

                                <label for="status">Select Status</label>
                                <select class="form-control show-tick" name="status" id="status" >
                                    <option>Due</option>
                                    <option>Full Paid</option>

                                </select>

                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </form>
    </div>
    @endsection

    @push('js')
            <!-- Select Plugin Js -->
    <script src="{{ asset('backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <!-- TinyMCE -->


    @endpush