routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('groupclient','GroupclientController');
    Route::resource('clientservice','ClientserviceController');
    Route::resource('client','ClientController');
    Route::get('clientReport','ClientController@clientReport')->name('clientReport');
   Route::get('/clientInvoice/{id}', 'ClientController@clientInvoice');



    Route::resource('groupsupplier','GroupsupplierController');
    Route::resource('supplier','SupplierController');
    Route::get('supplierReport','SupplierController@supplierReport')->name('supplierReport');
    Route::resource('item','ItemController');
    Route::resource('product','ProductController');
    Route::get('productReport','ProductController@productReport')->name('productReport');
    Route::resource('purchase','PurchaseController');
    Route::get('purchaseReport','PurchaseController@purchaseReport')->name('purchaseReport');
    Route::resource('retire','RetireController');
    Route::resource('invoice','InvoiceController');

});


Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('groupclient','GroupclientController');
    Route::resource('clientservice','ClientserviceController');
    Route::resource('client','ClientController');
    Route::get('clientReport','ClientController@clientReport')->name('clientReport');
    Route::get('/clientInvoice/{id}', 'ClientController@clientInvoice');
});

app/Groupclient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Groupclient extends Model
{
    public function clients()
    {
        return $this->belongsToMany('App\Client')->withTimestamps();
    }
}

app/Http/Controllers/Admin/GroupclientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Groupclient;
use Brian2694\Toastr\Facades\Toastr;
class GroupclientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groupclients= Groupclient::latest()->get();
        return view('admin.groupclient.index',compact('groupclients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.groupclient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',



        ]);

        $groupclient = new Groupclient;
        $groupclient->name = $request->name;
        $groupclient->save();
        Toastr::success('Client Group Successfully Saved :)','Success');
        return redirect(route('admin.groupclient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $groupclient= Groupclient::where('id',$id)->first();
        return view('admin.groupclient.edit',compact('groupclient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',

        ]);

        $groupclient = Groupclient::find($id);
        $groupclient->name = $request->name;
        $groupclient->save();
        Toastr::success('Client Group Successfully Updated :)','Success');
        return redirect(route('admin.groupclient.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Groupclient::where('id',$id)->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Author/GroupclientController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Groupclient;
use Brian2694\Toastr\Facades\Toastr;
class GroupclientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groupclients= Groupclient::latest()->get();
        return view('author.groupclient.index',compact('groupclients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('author.groupclient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',



        ]);

        $groupclient = new Groupclient;
        $groupclient->name = $request->name;
        $groupclient->save();
        Toastr::success('Client Group Successfully Saved :)','Success');
        return redirect(route('author.groupclient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $groupclient= Groupclient::where('id',$id)->first();
        return view('author.groupclient.edit',compact('groupclient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',

        ]);

        $groupclient = Groupclient::find($id);
        $groupclient->name = $request->name;
        $groupclient->save();
        Toastr::success('Client Group Successfully Updated :)','Success');
        return redirect(route('author.groupclient.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Groupclient::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/groupclient/create.blade.php
@extends('layouts.backend.app')

@section('title','Group Client')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ADD NEW GROUPCLIENT
                        </h2>
                    </div>
                    <div class="body">
                        <form action="{{ route('admin.groupclient.store') }}" method="POST" >
                            {{ csrf_field() }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="name" class="form-control" name="name">
                                    <label class="form-label">Name</label>
                                </div>
                            </div>


                            <a  class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.groupclient.index') }}">BACK</a>
                            <a  class="btn btn-info m-t-15 waves-effect" href="{{ route('admin.client.create') }}">ADD CLIENT</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')

@endpush

resources/views/admin/groupclient/edit.blade.php
@extends('layouts.backend.app')
@section('title','groupclient')
@push('css')
@endpush
@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Edit Client Group
                        </h2>
                    </div>
                    <div class="body">
                        <form action="{{ route('admin.groupclient.update',$groupclient->id) }}" method="POST" >
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="name" class="form-control" name="name" value="{{ $groupclient->name }}">
                                    <label class="form-label">Client Group Name</label>
                                </div>
                            </div>


                            <a  class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.groupclient.index') }}">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
@endpush 

resources/views/admin/groupclient/index.blade.php
@extends('layouts.backend.app')
@section('title','Group client')

@push('css')
        <!-- JQuery DataTable Css -->
<link href="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <a  class="btn bg-primary waves-effect " href="{{ route('admin.groupclient.create') }}">
                <i class="material-icons">add</i>
                <span>Add New Client Group</span>
            </a>
        </div>
        <!-- #END# Basic Examples -->
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            All Client Group
                            <span class="badge bg-blue">{{ $groupclients->count() }}</span>
                        </h2>

                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Name</th>
                                    <th>Created At </th>
                                    <th>Updated At </th>
                                    <th>Action</th>

                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>SL</th>
                                    <th>Name</th>
                                    <th>Created At </th>
                                    <th>Updated At </th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                                <tbody>



                                @foreach($groupclients as $groupclient)
                                    <tr>
                                        <td>{{ $loop->index + 1}}</td>
                                        <td>{{ $groupclient->name}}</td>
                                        <td>{{ $groupclient->created_at }}</td>
                                        <td>{{ $groupclient->updated_at }}</td>

                                        <td class="text-center">
                                            <a href="{{route('admin.groupclient.edit',$groupclient->id)}}" class="btn btn-primary waves-effect" >
                                                <i class="material-icons">edit</i>

                                            </a>
                                            <button class="btn btn-danger waves-effect" type="button" onclick="deletegroupclient({{ $groupclient->id }})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form id="delete-form-{{ $groupclient->id }}" action="{{ route('admin.groupclient.destroy',$groupclient->id) }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- #END# Exportable Table -->
    </div>
    @endsection

    @push('js')
            <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="{{ asset('backend/js/pages/tables/jquery-datatable.js') }}"></script>

    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
    <script type="text/javascript">
        function deletegroupclient(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-'+id).submit();
            }else if (
                    // Read more about handling dismissals
            result.dismiss === swal.DismissReason.cancel
            ) {
                swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                )
            }
        })
        }
    </script>
    @endpush